"""empty message

Revision ID: 25fe2325c346
Revises: 
Create Date: 2018-12-02 00:13:08.815358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fe2325c346'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_fortunes',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fortune_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_table('used_forturnes',
    sa.Column('row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_string', sa.String(), nullable=True),
    sa.Column('fortune_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('row_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_forturnes')
    op.drop_table('all_fortunes')
    # ### end Alembic commands ###
